version: 2

jobs:

  build-python36:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - model-cache
      - run: make model
      - save_cache:
          key: model-cache
          paths:
            models.tar.gz
            models
      - run: make install
      - run: git submodule update --init
      - run: make test

  build-python37:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - model-cache
      - run: make model
      - save_cache:
          key: model-cache
          paths:
            models.tar.gz
            models
      - run: make install
      - run: git submodule update --init
      - run: make test

workflows:
  version: 2
  build:
    jobs:
      - build-python36
      - build-python37
      #- build-python38 # no tensorflow for python 3.8
